[package]
authors = ["Adam Ierymenko <adam.ierymenko@zerotier.com>"]
edition = "2021"
license = "MPL-2.0"
name = "pp384"
version = "0.1.0"

[dependencies]

[dev-dependencies]
sha2 = "^0"
hex-literal = "^0"
